version: "3"
services:

  nginxproxy:
    build:
      context: dockers/nginx-proxy
    image: datasyntax/nginx-proxy
    container_name: vhost-proxy
    restart: always
    network_mode: "bridge"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${PROXY_HTTP_PORT:-80}:80"
      - "${PROXY_HTTPS_PORT:-443}:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /ssl_certs:/etc/nginx/certs:cached

  dns:
    image: jderusse/dns-gen
    container_name: dns
    restart: always
    network_mode: "bridge"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${DOCKER0_IP}:53:53/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN

  rsync:
    image: nabeken/docker-volume-container-rsync
    container_name: rsync
    restart: always
    network_mode: "bridge"
    ports:
      - "${DOCKER0_IP}:873:873"
    environment:
      - OWNER=root
      - GROUP=root
      - VOLUME=/projects
    volumes:
      - /projects
      - limesurvey-src:/projects/LimeSurvey
      - opencpu-src:/projects/OpenCPU
      - ppv3-src:/projects/PPV3
      - qjobber-src:/projects/QJobber
      - userv3-src:/projects/UserV3
      - adminv3-src:/projects/AdminV3
      - fegeneric-src:/projects/FEGeneric
      - fvs-src:/projects/FVS
      - edu-src:/projects/CENTERPARCS

  dummy:
    build:
      context: dockers/maintenance
    image: datasyntax/maintenance
    container_name: dummy
    restart: always
    network_mode: "bridge"
    environment:
      - MESSAGE="some custom message"
      - PORT=80
    env_file: .hosts.env

  openvpn:
    build:
     context: dockers/openvpn
    image: datasyntax/openvpn
    container_name: openvpn
    restart: always
    network_mode: "bridge"
    command: /usr/bin/run.sh
    ports:
       - "${DOCKER0_IP}:1194:1194"
    cap_add:
       - NET_ADMIN
    volumes:
       - ./openvpn/config:/etc/openvpn
       - ./openvpn/out:/tmp/out

volumes:
  limesurvey-src:
  opencpu-src:
  ppv3-src:
  qjobber-src:
  userv3-src:
  adminv3-src:
  fegeneric-src:
  fvs-src:
  edu-src:



